// libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging" % "3.1.0"
// libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging-api" % "2.1.2"
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging-slf4j" % "2.1.2"
libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.1.3"
// libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.1.2"
